name: Deploy Images to S3

on:
  workflow_dispatch:
    paths:
      - "images/**"

jobs:
  deploy-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload images to S3
        run: aws s3 sync images/ s3://my-image-cdn-bucket --acl public-read
